// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


import java.util.Date;

/************************************************************/
/**
 * 
 */
class Appointment {
	/**
	 * 
	 */
	public String appointmentID;
	/**
	 * 
	 */
	public Date startDateTime;
	/**
	 * 
	 */
	public Date endDateTime;
	/**
	 * 
	 */
	public String status;
	/**
	 * 
	 */
	public Receptionist receptionist;

	/**
	 * 
	 * @param patient 
	 */
	public void bookAppointment(Patient patient) {
	}

	/**
	 * 
	 * @param appointment 
	 */
	public void cancelAppointment(Appointment appointment) {
	}

	/**
	 * 
	 * @param appointment 
	 */
	public void rescheduleAppointment(Appointment appointment) {
	}
};
