// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------



import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Medicine {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public Date expiryDate;
	/**
	 * 
	 */
	public String composition;
};
