// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

/************************************************************/
/**
 * 
 */
public class Nurse extends Staff {
	/**
	 * 
	 */
	public String qualification;
	/**
	 * 
	 */
	public int experience;
	/**
	 * 
	 */
	public String specialization;
	/**
	 * 
	 */
	public Patient[] patient;
	/**
	 * 
	 */
	public Doctor[] doctor;

	/**
	 * 
	 * @param patient 
	 * @param doctor 
	 */
	public void assignDoctor(Patient patient, Doctor doctor) {
	}
};
