// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
/**
 * 
 */
public class Patient extends Person {
	/**
	 * 
	 */
	public String patientID;
	/**
	 * 
	 */
	public String healthInsurance;
	/**
	 * 
	 */
	public String allergies;
	/**
	 * 
	 */
	public String Smoking;
	/**
	 * 
	 */
	public String drinking;
	/**
	 * 
	 */
	public String drugs;
	/**
	 * 
	 */
	public Appointment[] appointment;
	/**
	 * 
	 */
	public Medicine medicine;
};
