// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


/************************************************************/
/**
 * 
 */
public class Receptionist extends Staff {
	/**
	 * 
	 * @param healthInsurance 
	 */
	public void validateInsurance(String healthInsurance) {
	}

	/**
	 * 
	 * @param patient 
	 */
	public void registerPatient(Patient patient) {
	}
};
