// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------



import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Staff extends Person {
	/**
	 * 
	 */
	public String staffID;
	/**
	 * 
	 */
	public String SIN;
	/**
	 * 
	 */
	public Date joiningDate;
	/**
	 * 
	 */
	public String status;

	/**
	 * 
	 * @param staff 
	 */
	public void registerStaff(Staff staff) {
	}
};
