// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

import java.util.Date;

/************************************************************/
/**
 * 
 */
class Appointment {
	/**
	 * 
	 */
	public String appointmentID;
	/**
	 * 
	 */
	public Date startDateTime;
	/**
	 * 
	 */
	public Date endDateTime;
	/**
	 * 
	 */
	public String status;
	/**
	 * 
	 */
	public Receptionist receptionist;

	/**
	 * 
	 * @param patient 
	 */
	public void bookAppointment(Patient patient) {
	}

	/**
	 * 
	 * @param appointment 
	 */
	public void cancelAppointment(HMS.Appointment appointment) {
	}

	/**
	 * 
	 * @param appointment 
	 */
	public void rescheduleAppointment(HMS.Appointment appointment) {
	}
};
