// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

/************************************************************/
/**
 * 
 */
class Bed {
	/**
	 * 
	 */
	public int bedNumber;
	/**
	 * 
	 */
	public Ward ward;

	/**
	 * 
	 */
	public void allocateBed() {
	}
};
