// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

/************************************************************/
/**
 * 
 */
public class Department {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public String departmentID;
	/**
	 * 
	 */
	public String description;
	/**
	 * 
	 */
	public Staff[] staff;

	/**
	 * 
	 * @param department 
	 */
	public void addDepartment(HMS.Department department) {
	}
};
