// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Doctor extends Staff {
	/**
	 * 
	 */
	public String qualification;
	/**
	 * 
	 */
	public int experience;
	/**
	 * 
	 */
	public String specialization;
	/**
	 * 
	 */
	public Patient[] patient;
	/**
	 * 
	 */
	public Appointment[] appointment;
	/**
	 * 
	 */
	public HMS.Doctor doctor;
	/**
	 * 
	 */
	public Prescription prescription;

	/**
	 * 
	 * @param date 
	 */
	public void cancelAllAppointments(Date date) {
	}
};
