// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

import java.util.Date;

/************************************************************/
/**
 * 
 */
class HealthReport {
	/**
	 * 
	 */
	public String id;
	/**
	 * 
	 */
	public Date createdDate;
	/**
	 * 
	 */
	public String createdBy;
	/**
	 * 
	 */
	public String medicalHistory;

	/**
	 * 
	 * @param Patient 
	 */
	public void dischargePatient(Patient Patient) {
	}
};
