// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Inpatient extends Patient {
	/**
	 * 
	 */
	public Date admissionDate;
	/**
	 * 
	 */
	public Date dischargeDate;
	/**
	 * 
	 */
	public Bed bed;
};
