// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

import java.util.Date;

/************************************************************/
/**
 * 
 */
public class Outpatient extends Patient {
	/**
	 * 
	 */
	public Date nextAppointment;
	/**
	 * 
	 */
	public HealthReport[] healthreport;

	/**
	 * 
	 * @param staff 
	 */
	public void registerStaff(Staff staff) {
	}
};
