// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

/************************************************************/
/**
 * 
 */
class Person {
	/**
	 * 
	 */
	public String name;
	/**
	 * 
	 */
	public String email;
	/**
	 * 
	 */
	public String dob;
	/**
	 * 
	 */
	public String address;
	/**
	 * 
	 */
	public String phoneNumber;
	/**
	 * 
	 */
	public String bloodGroup;
};
