// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

/************************************************************/
/**
 * 
 */
public class SystemAdministrator extends Staff {
	/**
	 * 
	 */
	public String role;
};
