// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package HMS;

/************************************************************/
/**
 * 
 */
public class Ward {
	/**
	 * 
	 */
	public int wardNumber;
	/**
	 * 
	 */
	public String capacity;
	/**
	 * 
	 */
	public Nurse[] nurse;

	/**
	 * 
	 * @param bed 
	 */
	public void addBed(Bed bed) {
	}
};
